Djangolvl5/Djangolvl5/urls.py
from django.contrib import admin
from django.urls import path, include
from ThePass import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('ThePass/', include("ThePass.urls")),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

Djangolvl5/ThePass/urls.py
from django.urls import path, include
from ThePass import views

app_name = "ThePass"

urlpatterns = [
    # path('home', views.index, name='index'),
    path('register', views.register, name='register'),
    path('user_login', views.user_login, name='user_login'),
]

Djangolvl5/ThePass/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='ThePass/profile_pics', blank=True)

    def __str__(self):
        return self.user.username

Djangolvl5/ThePass/forms.py
from django import forms
from django.contrib.auth.models import User
from ThePass.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

Djangolvl5/ThePass/views.py
from django.shortcuts import render
from ThePass.forms import UserForm, UserProfileInfoForm

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    return render(request, 'ThePass/index.html')

@login_required
def special(request):
    return HttpResponse("¡This is a Special location!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            user.save()

            registered = True
        
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'ThePass/registration.html', 
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if(user):
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            
            else:
                return HttpResponse("Account NOT active")
        
        else:
            print("An attempt has been made to login")
            print("Username : {} and Password : {}".format(username, password))
            return HttpResponse("Invalid login details!")
        
    else:
        return render(request, 'ThePass/login.css')

Djangolvl5/templates/ThePass/base.html
<!--
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src="{% static 'js/base.js' %}"></script>
    <title></title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark mb-5">
        <a class="navbar-brand" href="{% url 'index' %}">Phonesattire</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'ThePass:register' %}">Register</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link">Brands</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
            </ul>
        </div>
    </nav>

</body>
</html> -->

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        {# Django Home Link / Admin Link / Register Link#}
        <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'ThePass:register' %}">Register</a>

        {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
        {% else %}
          <a class="nav-item nav-link" href="{% url 'ThePass:user_login' %}">Login</a>
        {% endif %}
    </nav>

    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

Djangolvl5/templates/ThePass/index.html
{% extends 'ThePass/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Level Five</h1>
</div>

{% endblock %}

Djangolvl5/templates/ThePass/login.html
{% extends 'ThePass/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'ThePass:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username : </label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password : </label>
        <input type="password" name="password">

        <input type="submit" value="Login">
    </form>
</div>

{% endblock %}

Djangolvl5/templates/ThePass/registration.html
{% extends "ThePass/base.html" %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
    {% if registered %}
        <h2>Thank you for registering</h2>
    {% else %}
        <h2>Register Here</h2>
        <h4>Fill out the form:</h4>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Submit">
        </form>
    {% endif %}

</div>
{% endblock %}